import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import  {InfoHome}  from "@/components/InfoHome";
import  Footer  from "@/components/footer";
import { ReactLenis } from "lenis/dist/lenis-react";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis 
      root
      options={{
        // Learn more -> https://github.com/darkroomengineering/lenis?tab=readme-ov-file#instance-settings
        lerp: 0.05,
      }}>
        
        
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar/>
        
          <main className=" max-w-gxl mx-auto">

          </main>
          
        {children}
        <div className=" animate-pulse">
        
        

      </div>
        
        
      
      <Footer/>
      </body>
      
      </ReactLenis>
      
    </html>
    
  );
}
