import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import  {InfoHome}  from "@/components/InfoHome";
import  Footer  from "@/components/footer";
import { ReactLenis } from "lenis/dist/lenis-react";
import { RootProvider } from 'fumadocs-ui/provider';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      
        
        
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
          <ReactLenis 
      root
      options={{
        // Learn more -> https://github.com/darkroomengineering/lenis?tab=readme-ov-file#instance-settings
        lerp: 0.05,
      }}> 

          <Navbar/>
        
          
          
          <RootProvider>{children}</RootProvider>

        
        
      
          </ReactLenis>
      </body>
      
      
      
    </html>
    
  );
}
